### ISSUE TITLE
Dropdown menus

### ISSUE THREAD

**Issue by nikapadia** [nikapadia/SuperSnippets#5]
When you click export, share, or any other item in the toolbar a dropdown menu should appear. 

Example:
![image](https://github.com/nikapadia/SuperSnippets/assets/30702376/3a16c0d1-fe92-4a4b-8ca2-cd8f00102e7b)

**Comment by crizbae** [comment]
IM SO GOATED AT DROPDOWN MENUS 🥱

**Comment by crizbae** [comment]
yeah im kind of the goat???
